### ISSUE TITLE
different VISUAL in instance view when "not running = stoped" / "maintenance" / "error"

### ISSUE THREAD

**Issue by lomadi** [bibbox/sys-bibbox-frontend#16]
show clear difference between 
- running
- running + maintenance on
- not running because stoped
- not running because an error (state in backend = running but containers are not present)

**Comment by Balfear** [comment]
Right now, we do not have this information in the GUI. We need to get more exact instance status information from API.

**Comment by Balfear** [comment]
Instances on the Applications menu are now differently visualized depending on whether they are running, stopped, installing or maintenance.
Closing.
