### ISSUE TITLE
Merge dashboard and logs with tabs

### ISSUE THREAD

**Issue by Balfear** [bibbox/sys-bibbox-frontend#17]
The dashboard and logs screens of an application should provide some kinde of tab-navigation to switch between them faster. Also, the application controls should also be available while viewing the logs.

**Comment by Balfear** [comment]
![dashboard-raw-concept](https://cloud.githubusercontent.com/assets/2675688/23955751/23ba58c8-099b-11e7-9848-1ff98e85098b.png)

**Comment by Balfear** [comment]
Please make sure, all needed data is provided by the API. Also provide all application status information in the logs and metadata APIs.

**Comment by reihsr** [comment]
Is updated and deployed on dev server

**Comment by Balfear** [comment]
Please also provide the docker containers and URL to the app's docs.
If no docs are present, maybe send the publisher website link instead?

**Comment by Balfear** [comment]
Created a new issue for this in YouTrack. Closing this here
