### ISSUE TITLE
Data send in the installer (json)

### ISSUE THREAD

**Issue by reihsr** [bibbox/sys-bibbox-frontend#6]
The parameter in the install request is send as a:
{MYSQL_PASSWORD=uu, INSTITUTE_NAME=BIBBOX Demo Biobank, MYSQL_USER=openspecimen, TOMCAT_MANAGER_USER=admin, TOMCAT_MANAGER_PASSWORD=uu}
Not as json.

**Comment by Balfear** [comment]
JSON data is formatted and send correctly in the frontend. Might be an issue in JAVA?
Closing for now.
